export const SCREEN_NAME: ScreenNameObjectType = {
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  SETTING: 'SETTING',
  ADD_TABLE: 'ADD_TABLE',
  HOME: 'HOME',
  DRAWER_STACK: 'DRAWER_STACK',
  ADD_MERCHANDISE: 'ADD_MERCHANDISE',
  ADD_MERCHANDISE_GROUP: 'ADD_MERCHANDISE_GROUP',
  ADD_UNIT_MERCHANDISE: 'ADD_UNIT_MERCHANDISE',
  MERCHANDISE: 'MERCHANDISE',
  ORDER_DETAIL: 'ORDER_DETAIL',
  ADD_ORDER: 'ADD_ORDER',
  REVENUE: 'REVENUE',
  REVENUE_BY_DATE: 'REVENUE_BY_DATE',
  REVENUE_BY_DATE_DETAIL: 'REVENUE_BY_DATE_DETAIL',
};

type ScreenNameObjectType = {
  LOGIN: 'LOGIN';
  SIGN_UP: 'SIGN_UP';
  SETTING: 'SETTING';
  ADD_TABLE: 'ADD_TABLE';
  HOME: 'HOME';
  DRAWER_STACK: 'DRAWER_STACK';
  ADD_MERCHANDISE: 'ADD_MERCHANDISE';
  ADD_MERCHANDISE_GROUP: 'ADD_MERCHANDISE_GROUP';
  ADD_UNIT_MERCHANDISE: 'ADD_UNIT_MERCHANDISE';
  MERCHANDISE: 'MERCHANDISE';
  ORDER_DETAIL: 'ORDER_DETAIL';
  ADD_ORDER: 'ADD_ORDER';
  REVENUE: 'REVENUE';
  REVENUE_BY_DATE: 'REVENUE_BY_DATE';
  REVENUE_BY_DATE_DETAIL: 'REVENUE_BY_DATE_DETAIL';
};

export type ScreenNameType = keyof typeof SCREEN_NAME;
